[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spl_token_project = "Auj3EUALzzuHvtU7BgbwArCP8qWe5V6EU2V56sP7Wuqk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
